### ISSUE TITLE
Przetłumaczenie headlineów artykułów na język polski

### ISSUE THREAD

**Issue by RubasznyRabarbar** [spio2018/cryptocharts#20]
Jako użytkownik chciałbym mieć możliwość wyświetlania  headlinów artykułów w języku polskim

**Comment by gogsson** [comment]
https://businessinsider.com.pl/finanse/kryptowaluty/czym-sa-bitcoiny-i-kryptowaluty/05f5ned

**Comment by gogsson** [comment]
Regulacje prawne na świecie:
https://bithub.pl/artykuly/status-prawny-kryptowalut-na-swiecie-rok-2018/

**Comment by gogsson** [comment]
Opinie na temat Bitcoina: https://businessinsider.com.pl/finanse/kryptowaluty/bitcoin-czy-jest-banka-opinie-szefow-bankow-i-ekonomistow/s3qgjey

Opinie ekonomistów na temat kryptowalut: https://businessinsider.com.pl/finanse/kryptowaluty/czy-kryptowaluty-zastapia-waluty-i-pieniadze-opinia-jp-morgan/zy7r0xd

**Comment by RubasznyRabarbar** [comment]
Baze wiedzy weźmiemy po polsku - artykuł pierwszy. 

[Prawo] Legalne środowisko wokół Bitcoina
Wraz z wzostem popytu na kryptowaluty, globalni regulatorzy są podzieleni jak za tym nadążyć. W Większości kryptowaluty nie są wspierane przez rządy, co znaczy, że każdy kraj ma inne standardy. W tym krótkim poradniku omówimy jak w większości regulatorzy i rządy radzą sobie z tym problemem .
[Opinie] W co inwestować ? 
Rynek finansowy zmienia się, wielu ludzi uświadomiło to sobie w momencie gdy Bitcoin i inne kryptowaluty stały się gorącym tematem. Teraz gdy jesteśmy w roku 2018 możemy bezpiecznie powiedzieć, że kryptowaluty są mocniejsze niż kiedykolwiek. Z wieloma inwestycjami które możnaby wykorzystać.

**Comment by RubasznyRabarbar** [comment]
[Baza wiedzy] Abc kryptowalut
Kryptowaluta jest środkiem wymiany jak normalne waluty typu dolar, jednak skonstruowana na potrzeby wymiany informacji poprzez proces używający określonych zasad z kryptografii. Kryptografia pozwala zabezpieczyć te transakcje i tworzenie nowych jednostek waluty. Pierwsza kryptowaluta czyli Bitcoin była stworzona w 2009 roku

**Comment by RubasznyRabarbar** [comment]
Pośród mniej znanych największymi zwycięzcami są m.in. Stellar Lumens, IOTA, EOS.
